name: commerce
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.0
  get: ^4.6.5
  device_preview: ^1.1.0
  http: ^1.1.0
  shared_preferences: ^2.2.1
  carousel_slider: ^4.2.1
  pin_code_fields: ^8.0.1
  connectivity_plus: ^5.0.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/images/
